### ISSUE TITLE
Mi Desk Lamp - Firmware 1.3.0 issue

### ISSUE THREAD

**Issue by ghost** [davidramiro/fluxee#6] opened 2019-02-10 22:57 UTC
Have you tested Fluxee with the latest firmware ? It seems I can't communicate with the lamp anymore.

**Comment by davidramiro** [comment] 2019-03-25 11:49
Sorry for the late reply! I just tested it on 1.3.7_058, there definitely seems to be an issue. The Mi Desk Lamp always had some responsiveness issues, but now it is only accepting maybe 1 out of 10 commands. 

I will try to contact the Yeelight devs, I suppose it's on them to figure this out...

**Comment by davidramiro** [comment] 2019-06-14 18:55
After three months the Yeelight team finally reported back, they will have a look into it. Also another user confirmed the issue, so I suppose this is not an issue with the script itself. Hence I will close this issue although I will keep you posted if there is any further development.

**Closed as completed by davidramiro** 2019-06-14 18:55 UTC
Labels: bug
